plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
RSpec/ExampleLength:
  Max: 30
RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
    Max: 5
