name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  RSpec:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2', '3.3', '3.4' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build
      run: |
        bundle install
        bundle exec rspec

  Rubocop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Rubocop
        run: | 
          bundle install
          bundle exec rubocop
